Models/ErrorViewModel.cs
using System;

namespace SandulasWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MyAnchorTagHelper.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc.TagHelpers;
using Microsoft.AspNetCore.Mvc.ViewFeatures;
using Microsoft.AspNetCore.Razor.TagHelpers;

namespace SandulasWebApp.Models
{
	//https://damienbod.com/2018/08/13/is-active-route-tag-helper-for-asp-net-mvc-core-with-razor-page-support/

	[HtmlTargetElement("a", Attributes = "select-current-route")]
	public class MyAnchorTagHelper : AnchorTagHelper
	{
		public MyAnchorTagHelper(IHtmlGenerator generator) : base(generator) { }

		public override int Order { get { return 1; } }

		public override void Process(TagHelperContext context, TagHelperOutput output)
		{
			output.Attributes.RemoveAll("select-current-route");

			if (!isCurrentRoute()) return;

			//add "selected" value to the "class" attribute
			var classAttr = output.Attributes.FirstOrDefault(a => a.Name == "class");
			if (classAttr == null)
			{
				output.Attributes.Add("class", "selected");
			}
			else if (classAttr.Value == null)
			{
				output.Attributes.SetAttribute("class", "selected");
			}
			else if (!classAttr.Value.ToString().ToLower().Contains("selected"))
			{
				output.Attributes.SetAttribute("class", classAttr.Value.ToString() + " selected");
			}

			//remove the "href" attribute
			var hrefIndex = output.Attributes.IndexOfName("href");
			if (hrefIndex > - 1) output.Attributes.RemoveAt(hrefIndex);
		}

		private bool isCurrentRoute()
		{
			string currentController = ViewContext.RouteData.Values["Controller"].ToString();
			string currentAction = ViewContext.RouteData.Values["Action"].ToString();

			if (!string.IsNullOrWhiteSpace(Controller) && Controller.ToLower() != currentController.ToLower())
			{
				return false;
			}

			if (!string.IsNullOrWhiteSpace(Action) && Action.ToLower() != currentAction.ToLower())
			{
				return false;
			}

			return true;
		}
	}
}

Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SandulasWebApp.Models;

namespace SandulasWebApp.Controllers
{
	public class MainController : Controller
	{
		public IActionResult About()
		{
			return View();
		}

		public IActionResult Resume()
		{
			ViewData["Message"] = "Under construction";

			return View();
		}

		public IActionResult Chatbot()
		{
			ViewData["Message"] = "Under construction";

			return View();
		}

		public IActionResult Contact()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

Pages/Test.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace SandulasWebApp.Pages
{
	public class TestModel : PageModel
	{
		public int Id { get; set; }
		public void OnGet(int id)
		{
			Id = id;
		}
	}
}

Pages/Test.cshtml
@page "{id=null}"
@using SandulasWebApp.Pages
@model TestModel
@{
	ViewData["Title"] = "Test Razor Page";
}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - SandulasWebApp</title>
</head>
<body>
	Test razor page<br />
	Id: @Model.Id
</body>
</html>

Views/Main/About.cshtml
@{
	ViewData["Title"] = "About Me";
}

<div class="content-flexbox about-item-left">
	<div></div>
	<div>
		<img src="~/images/about1.jpg" />
		<div>
			<p>I'm a software engineer.</p>
			<p>
				I've started my career in 2001 as a full-stack web developer.<br />
				I've worked as a backend developer, team leader and product manager (<a asp-controller="Main" asp-action="Resume">resume</a>).
			</p>
			<p>I was born in 1980, I live in Bucharest, I'm married and I have a son.</p>
		</div>
	</div>
	<div></div>
</div>

<div class="content-flexbox about-item-right">
	<div></div>
	<div>
		<div>
			<p>I'm passionate about cutting edge technology and science.</p>
			<p>
				I find the recent advancements in Artificial Intelligence, Quantum Computing,<br />
				VR / AR, Space Exploration, Genomics and Neuroscience particularly interesting.
			</p>
		</div>
		<img src="~/images/about2.jpg" />
	</div>
	<div></div>
</div>

<div class="content-flexbox about-item-left">
	<div></div>
	<div>
		<img src="~/images/about3.jpg" />
		<div>
			<p>I love nature, mountain hikes and motorcycles.</p>
			<p>
				I like to travel, especially in remote places and rural areas.<br />
				I also like books, rock music and beer.
			</p>
		</div>
	</div>
	<div></div>
</div>

Views/Main/Chatbot.cshtml
@{
	ViewData["Title"] = "Chatbot";
}

<div class="content-flexbox">
	<div></div>
	<div>
		<p>@ViewData["Message"]</p>
	</div>
	<div></div>
</div>

Views/Main/Contact.cshtml
@{
	ViewData["Title"] = "Contact";
}

<div class="content-flexbox">
	<div></div>
	<div>
		<address>
			<p>Bucharest, Romania</p>
		</address>
		<address>
			<p><a href="mailto:sandulas@gmail.com">sandulas@gmail.com</a></p>
		</address>
	</div>
	<div></div>
</div>


Views/Main/Resume.cshtml
@{
    ViewData["Title"] = "Resume";
}

<div class="content-flexbox">
	<div></div>
	<div>

		<!-- Experience -->
		<div class="resume-header">
			<img src="~/images/icon-experience.png" /><h2>Experience</h2>
		</div>
		<div class="resume-content">
			<p>
				<img src="~/images/circle.svg" />Senior Backend Developer, Product Manager<br />
				<span><b>Nov 2012 - Present,</b> Pronetis Games</span>
			</p>
			<ul>
				<li><span>Develop backend applications, API's and tools to support games with over 20 million total players and over 100k daily active users.</span></li>
				<li><span>Recruit and train developers.</span></li>
				<li><span>Implement project management methodologies, introduce tools and practices to maximize efficiency.</span></li>
				<li><span>Implement analytics, define and monitor KPIs.</span></li>
				<li><span>Create original game concepts, UX, game design, level design.</span></li>
			</ul>
		</div>
		<div class="resume-content">
			<p>
				<img src="~/images/circle.svg" />Team Lead (Web Development)<br />
				<span><b>Aug 2007 - Nov 2012,</b> Pronetis</span>
			</p>
			<ul>
				<li><span>Create and document technical specifications.</span></li>
				<li><span>Application architecture design (define modules and interactions, services, APIs).</span></li>
				<li><span>Project management (define milestones, workload management, tasks assignment and prioritization).</span></li>
				<li><span>Client communication (clarify the scope of the projects, report progress, accommodate new requests, re-evaluate timelines).</span></li>
			</ul>
		</div>
		<div class="resume-content">
			<p>
				<img src="~/images/circle.svg" />Full Stack Web Developer<br />
				<span><b>Oct 2002 - Aug 2007,</b> Telemach</span>
			</p>
			<ul>
				<li><span>Develop, deploy and maintain web applications.</span></li>
				<li><span>Design and optimize relational databases.</span></li>
				<li><span>Integrate external SDKs and APIs.</span></li>
			</ul>
		</div>
		<div class="resume-content">
			<p>
				<img src="~/images/circle.svg" />Junior Web Developer<br />
				<span><b>Oct 2001 - Oct 2002,</b> Internet Software Design</span>
			</p>
			<ul>
				<li><span>Develop and maintain websites.</span></li>
				<li><span>Create Flash animations and interactive presentations.</span></li>
			</ul>
			<div></div>
		</div>

		<!-- Projects -->
		<div class="resume-header">
			<img src="~/images/icon-projects.png" /><h2>Projects</h2>
		</div>
		<div class="resume-content">
			<p><img src="~/images/circle.svg" />Web Applications</p>
			<ul>
				<li><span>National Geographic Channel Global Web Platform (client facing websites and CMS) - <a href="http://natgeotv.com" target="_blank">natgeotv.com</a>.</span></li>
				<li><span>Fox International Channels Asia Websites.</span></li>
				<li><span>Fox TV UK Website - <a href="http://foxtv.co.uk" target="_blank">foxtv.co.uk</a>.</span></li>
				<li><span>I Can, Can U - a social platform for "favour" sharing.</span></li>
			</ul>
		</div>
		<div class="resume-content">
			<p><img src="~/images/circle.svg" />Games</p>
			<ul>
				<li><span>GyroSphere Evolution -
					<a href="https://itunes.apple.com/ro/app/gyrosphere-evolution/id1261265238?mt=8" target="_blank">iOS</a>,
					<a href="https://play.google.com/store/apps/details?id=com.pronetis.gyrosphereevolution&hl=en" target="_blank">Android</a>,
					<a href="https://gyrosphereevolution.com/" target="_blank">Website</a>.</span></li>
				<li><span>GyroSphere Trials -
					<a href="https://store.steampowered.com/app/673280/GyroSphere_Trials/" target="_blank">PC</a>,
					<a href="https://itunes.apple.com/us/app/gyrosphere-trials/id1035238692?mt=8" target="_blank">iOS</a>,
					<a href="https://play.google.com/store/apps/details?id=com.pronetis.gyrosphere&hl=en" target="_blank">Android</a>.</span></li>
				<li><span>3D Sketch Studio -
					<a href="https://itunes.apple.com/ro/app/3d-sketch-studio/id881447162?mt=12" target="_blank">Mac</a>,
					<a href="https://itunes.apple.com/us/app/3d-sketch-studio/id786120101?mt=8" target="_blank">iOS</a>,
					<a href="https://play.google.com/store/apps/details?id=com.crocostudio.sketchandstretch&hl=en" target="_blank">Android</a>.</span></li>
				<li><span>Build and Play 3D -
					<a href="https://itunes.apple.com/us/app/build-and-play/id545626598?mt=8" target="_blank">iOS</a>,
					<a href="https://play.google.com/store/apps/details?id=com.crocostudio.buildandplay&hl=en_US" target="_blank">Android</a>.</span></li>
				<li><span>Fairytale Sort and Stack -
					<a href="https://itunes.apple.com/us/app/fairytale-sort-and-stack/id655508309?mt=8" target="_blank">iOS</a>,
					<a href="https://play.google.com/store/apps/details?id=com.crocostudio.fairytalesortandstack&hl=en" target="_blank">Android</a>.</span></li>
			</ul>
		</div>
		<div class="resume-content">
			<p><img src="~/images/circle.svg" />Personal</p>
			<ul>
				<li><span><a href="http://sandulas.xyz" target="_blank">sandulas.xyz</a> - personal website.</span></li>
				<li><span>Mechanics Playground - proof of concept for basic 2D physics in Unity -
					<a href="https://itunes.apple.com/us/app/mechanics-playground/id1058417101?mt=8" target="_blank">iOS</a>,
					<a href="https://drive.google.com/file/d/0B3gyd8mDsXNlTm9xbGlhWlE1aEk/view?usp=sharing" target="_blank">Video</a>.</span></li>
				<li><span>Tumble Up! - small action-puzzle game created in 24 hours at Ubisoft GameJam 2015.</span></li>
			</ul>
			<div></div>
		</div>

		<!-- Skills -->
		<div class="resume-header">
			<img src="~/images/icon-skills.png" /><h2>Skills</h2>
		</div>
		<div class="resume-content">
			<p><img src="~/images/circle.svg" />Development</p>
			<ul>
				<li><span>ASP.NET, ASP.NET Core - MVC, Web API, Razor Pages, Web Forms.</span></li>
				<li><span>C#, SQL, Javascript, HTML, CSS.</span></li>
				<li><span>Relational database design and optimization, Microsoft SQL Server.</span></li>
				<li><span>Microsoft Azure - Bot Framework, QnAMaker, App Services.</span></li>
				<li><span>Unity 3D Game Engine.</span></li>
			</ul>
		</div>
		<div class="resume-content">
			<p><img src="~/images/circle.svg" />Software, Tools</p>
			<ul>
				<li><span>Trello, Photoshop, Draw.io, Google Docs.</span></li>
				<li><span>GIT, Selenium, Postman, Curl.</span></li>
				<li><span>Windows, Mac OS, Linux.</span></li>
			</ul>
		</div>
		<div class="resume-content">
			<p><img src="~/images/circle.svg" />Project Management</p>
			<ul>
				<li><span>Scrum, Kanban, Watterfall.</span></li>
				<li><span>Burndown Charts, Kanban Boards, Flow Diagrams, Gantt Charts.</span></li>
			</ul>
		</div>
		<div class="resume-content">
			<p><img src="~/images/circle.svg" />Languages</p>
			<ul>
				<li><span>English - advanced.</span></li>
				<li><span>Romanian - native.</span></li>
			</ul>
			<div></div>
		</div>


		<!-- Education -->
		<div class="resume-header">
			<img src="~/images/icon-education.png" /><h2>Education</h2>
		</div>
		<div class="resume-content">
			<p>
				<img src="~/images/circle.svg" />Electronics and Telecommunications<br />
				<span><b>1998 - 2002,</b> "Politehnica" University of Bucharest (not finished)</span>
			</p>
		</div>
		<div class="resume-content">
			<p>
				<img src="~/images/circle.svg" />Computer Science<br />
				<span><b>1994 - 1998,</b> "Ion Barbu" High School, Pitesti</span>
			</p>
			<div></div>
		</div>

	</div>
	<div></div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<link rel="icon" href="~/images/favicon.png" />
	<title>Adrian Sandu - @ViewData["Title"]</title>

	<link rel="stylesheet" href="~/css/main.css" asp-append-version="true" />
</head>
<body>

	<div>
		<header>
			<div></div>
			<div>
				<div>
					<a asp-controller="Main" asp-action="Contact" class="title">Adrian Sandu<br /><span>@@sandulas</span></a>

					<a id="navMenuIcon" href="javascript:void(0)" onclick="showHideMenu();"></a>
					<div id="navMenu">
						<a asp-controller="Main" asp-action="About" select-current-route>About Me</a><br />
						<a asp-controller="Main" asp-action="Resume" select-current-route>Resume</a><br />
						<a asp-controller="Main" asp-action="Chatbot" select-current-route>Chatbot</a><br />
						<a asp-controller="Main" asp-action="Contact" select-current-route>Contact</a>
					</div>

					<a asp-controller="Main" asp-action="About" class="nav left" select-current-route>About Me</a>
					<a asp-controller="Main" asp-action="Resume" class="nav left" select-current-route>Resume</a>
				</div>
				<div>
					<a asp-controller="Main" asp-action="About" class="avatar"><img src="~/images/avatar.jpg" /></a>
				</div>
				<div>
					<a asp-controller="Main" asp-action="Chatbot" class="nav right" select-current-route>Chatbot</a>
					<a asp-controller="Main" asp-action="Contact" class="nav right" select-current-route>Contact</a>
				</div>
			</div>
			<div></div>
		</header>

		<div class="content-flexbox">
			<div></div>
			<div>
				<h1>@ViewData["Title"]</h1>
			</div>
			<div></div>
		</div>

		@RenderBody()

	</div>

	<div class="content-flexbox footer">
		<div></div>
		<div>
			<footer>
				&copy; @DateTime.Now.Year - Adrian Sandu
			</footer>
		</div>
		<div></div>
	</div>

	@RenderSection("Scripts", required: false)

	@*<div style="position: absolute; top: 5px; right: 5px;">Viewport size - <span id="viewWidthDisplay"></span> : <span id="viewHeightDisplay"></span></div>*@

	<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"></script>
	<script>
		@*
		$(document).ready(function(e) {
			showViewportSize();
		});

		$(window).resize(function(e) {
		   showViewportSize();
		});
		*@

		function showViewportSize() {
			var viewWidth = $(window).width();
			var viewHeight = $(window).height();
			$('#viewWidthDisplay').text(viewWidth);
			$('#viewHeightDisplay').text(viewHeight);
		}

		function showHideMenu() {
			if ($("#navMenu").is(":visible"))
			{
				$('#navMenuIcon').removeClass("on");
				$('#navMenu').hide();
			}
			else
			{
				$('#navMenuIcon').addClass("on");
				$('#navMenu').show();
			}
		}
	</script>

</body>
</html>